[app]
version = "0.0.1"

[toaster]
titles = [
    "bbbb",
    "提醒标题2",
]
contents = [
    "傻逼",
    "提醒内容2",
]
interval_time = 1
duration = 5
color_1 = "#FF0000"
color_2 = "#4ECDC4"
content_switch_mode = "random"
